-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2023-11-17 18:19:43 AEDT
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c
--   Student names: Liana Rigby (28778464), Hooman Riahi (30068568), Wilson Wong(29704154)
--   group#:    G42  

SET ECHO ON
SPOOL mau_schema_output.txt


DROP TABLE artist CASCADE CONSTRAINTS;

DROP TABLE artwork CASCADE CONSTRAINTS PURGE;

DROP TABLE artwork_media CASCADE CONSTRAINTS PURGE;

DROP TABLE artwork_style CASCADE CONSTRAINTS PURGE;

DROP TABLE customer CASCADE CONSTRAINTS PURGE;

DROP TABLE exhibit CASCADE CONSTRAINTS PURGE;

DROP TABLE gallery CASCADE CONSTRAINTS PURGE;

DROP TABLE history CASCADE CONSTRAINTS PURGE;

DROP TABLE sale CASCADE CONSTRAINTS PURGE;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE artist (
    artist_code            NUMBER(4) NOT NULL,
    artist_gname           VARCHAR2(20) NOT NULL,
    artist_fname           VARCHAR2(20) NOT NULL,
    artist_contact_address VARCHAR2(100) NOT NULL,
    artist_phone           CHAR(12),
    artist_num_artworks    NUMBER(3) NOT NULL,
    artist_code1           NUMBER(4)
);

COMMENT ON COLUMN artist.artist_code IS
    'Artist code';

COMMENT ON COLUMN artist.artist_gname IS
    'Artist''s given name';

COMMENT ON COLUMN artist.artist_fname IS
    'Artist''s family name';

COMMENT ON COLUMN artist.artist_contact_address IS
    'Artist''s contact address';

COMMENT ON COLUMN artist.artist_phone IS
    'Artist''s phone number';

COMMENT ON COLUMN artist.artist_num_artworks IS
    'The number of artworks created by the artist';

COMMENT ON COLUMN artist.artist_code1 IS
    'Artist code';

ALTER TABLE artist ADD CONSTRAINT artist_pk PRIMARY KEY ( artist_code );

CREATE TABLE artwork (
    art_number         NUMBER(3) NOT NULL,
    artist_code        NUMBER(4) NOT NULL,
    art_title          VARCHAR2(50) NOT NULL,
    art_date_accepted  DATE NOT NULL,
    art_min_sell_price NUMBER(10, 2) NOT NULL,
    art_media_id       NUMBER(4) NOT NULL,
    art_style_id       NUMBER(4) NOT NULL
);

COMMENT ON COLUMN artwork.art_number IS
    'Artwork number';

COMMENT ON COLUMN artwork.artist_code IS
    'Artist code';

COMMENT ON COLUMN artwork.art_title IS
    'Artwork title';

COMMENT ON COLUMN artwork.art_date_accepted IS
    'Date the art was accepted to mau';

COMMENT ON COLUMN artwork.art_min_sell_price IS
    'The minimum sell price of the artwork';

COMMENT ON COLUMN artwork.art_media_id IS
    'Artwork media ID';

COMMENT ON COLUMN artwork.art_style_id IS
    'Artwork style ID';

ALTER TABLE artwork ADD CONSTRAINT artwork_pk PRIMARY KEY ( art_number,
                                                            artist_code );

CREATE TABLE artwork_media (
    art_media_id   NUMBER(4) NOT NULL,
    art_media_desc VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN artwork_media.art_media_id IS
    'Artwork media ID';

COMMENT ON COLUMN artwork_media.art_media_desc IS
    'Description of artwork media';

ALTER TABLE artwork_media ADD CONSTRAINT artwork_media_pk PRIMARY KEY ( art_media_id )
;

CREATE TABLE artwork_style (
    art_style_id   NUMBER(4) NOT NULL,
    art_style_desc VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN artwork_style.art_style_id IS
    'Artwork style ID';

COMMENT ON COLUMN artwork_style.art_style_desc IS
    'Artwork style description';

ALTER TABLE artwork_style ADD CONSTRAINT artwork_stlye_pk PRIMARY KEY ( art_style_id )
;

CREATE TABLE customer (
    cust_id            NUMBER(7) NOT NULL,
    cust_name          VARCHAR2(50) NOT NULL,
    cust_address       VARCHAR2(100) NOT NULL,
    cust_contact_phone CHAR(12) NOT NULL,
    cust_business_name VARCHAR2(50)
);

COMMENT ON COLUMN customer.cust_id IS
    'Customer ID';

COMMENT ON COLUMN customer.cust_name IS
    'Customer personal name';

COMMENT ON COLUMN customer.cust_address IS
    'Customer address';

COMMENT ON COLUMN customer.cust_contact_phone IS
    'Customer phone number';

COMMENT ON COLUMN customer.cust_business_name IS
    'Customer business name';

ALTER TABLE customer ADD CONSTRAINT customer_pk PRIMARY KEY ( cust_id );

CREATE TABLE exhibit (
    exhibit_no           NUMBER(7) NOT NULL,
    gal_id               NUMBER(4) NOT NULL,
    artist_code          NUMBER(4) NOT NULL,
    art_number           NUMBER(3) NOT NULL,
    exhibit_start_date   DATE NOT NULL,
    exhibit_end_date     DATE,
    exhibit_art_featured CHAR(1) NOT NULL
);

ALTER TABLE exhibit
    ADD CONSTRAINT chk_exhibit_art_featured CHECK ( exhibit_art_featured IN ( 'N', 'Y'
    ) );

COMMENT ON COLUMN exhibit.exhibit_no IS
    'Exhibit number';

COMMENT ON COLUMN exhibit.gal_id IS
    'Gallery ID';

COMMENT ON COLUMN exhibit.artist_code IS
    'Artist code';

COMMENT ON COLUMN exhibit.art_number IS
    'Artwork number';

COMMENT ON COLUMN exhibit.exhibit_start_date IS
    'Exhibit start date';

COMMENT ON COLUMN exhibit.exhibit_end_date IS
    'Exhibit end date';

COMMENT ON COLUMN exhibit.exhibit_art_featured IS
    'Exhibit art featured in catalogue (Y=Yes, N=No)';

ALTER TABLE exhibit ADD CONSTRAINT exhibit_pk PRIMARY KEY ( exhibit_no );

ALTER TABLE exhibit
    ADD CONSTRAINT exhibit_nk UNIQUE ( artist_code,
                                       art_number,
                                       gal_id,
                                       exhibit_start_date );

CREATE TABLE gallery (
    gal_id            NUMBER(4) NOT NULL,
    gal_name          VARCHAR2(50) NOT NULL,
    gal_manager       VARCHAR2(50) NOT NULL,
    gal_street        VARCHAR2(20) NOT NULL,
    gal_town          VARCHAR2(20) NOT NULL,
    gal_state         VARCHAR2(20) NOT NULL,
    gal_contact_phone CHAR(12) NOT NULL,
    gal_commission    NUMBER(2, 2) NOT NULL,
    gal_open          DATE,
    gal_close         DATE
);

COMMENT ON COLUMN gallery.gal_id IS
    'Gallery ID';

COMMENT ON COLUMN gallery.gal_name IS
    'Gallery name';

COMMENT ON COLUMN gallery.gal_manager IS
    'Gallery Manager''s Name';

COMMENT ON COLUMN gallery.gal_street IS
    'Gallery street address';

COMMENT ON COLUMN gallery.gal_town IS
    'Gallery town address';

COMMENT ON COLUMN gallery.gal_state IS
    'Gallery state address';

COMMENT ON COLUMN gallery.gal_contact_phone IS
    'Gallery contact phone number';

COMMENT ON COLUMN gallery.gal_commission IS
    'Gallery commission (XX.XX%)';

COMMENT ON COLUMN gallery.gal_open IS
    'Gallery open time';

COMMENT ON COLUMN gallery.gal_close IS
    'Gallery closing time';

ALTER TABLE gallery ADD CONSTRAINT gallery_pk PRIMARY KEY ( gal_id );

CREATE TABLE history (
    hist_no     NUMBER(7) NOT NULL,
    artist_code NUMBER(4) NOT NULL,
    art_number  NUMBER(3) NOT NULL,
    hist_date   DATE NOT NULL,
    hist_status CHAR(1) NOT NULL,
    gal_id      NUMBER(4)
);

ALTER TABLE history
    ADD CONSTRAINT chk_hist_status CHECK ( hist_status IN ( 'D', 'R', 'S', 'T', 'W' )
    );

COMMENT ON COLUMN history.hist_no IS
    'History Number';

COMMENT ON COLUMN history.artist_code IS
    'Artist code';

COMMENT ON COLUMN history.art_number IS
    'Artwork number';

COMMENT ON COLUMN history.hist_date IS
    'History date';

COMMENT ON COLUMN history.hist_status IS
    'History status (W=Warehouse storage, T=Transit, D=Display, S=Sold, R=Returned to artist)'
    ;

COMMENT ON COLUMN history.gal_id IS
    'Gallery ID';

ALTER TABLE history ADD CONSTRAINT history_pk PRIMARY KEY ( hist_no );

ALTER TABLE history
    ADD CONSTRAINT history_nk UNIQUE ( hist_date,
                                       artist_code,
                                       art_number,
                                       hist_status );

CREATE TABLE sale (
    sale_id    NUMBER(7) NOT NULL,
    sale_date  DATE NOT NULL,
    sale_price NUMBER(8, 2) NOT NULL,
    cust_id    NUMBER(7) NOT NULL,
    exhibit_no NUMBER(7) NOT NULL
);

COMMENT ON COLUMN sale.sale_id IS
    'Sale ID';

COMMENT ON COLUMN sale.sale_date IS
    'Sale date';

COMMENT ON COLUMN sale.sale_price IS
    'Sale price';

COMMENT ON COLUMN sale.cust_id IS
    'Customer ID';

COMMENT ON COLUMN sale.exhibit_no IS
    'Exhibit number';

ALTER TABLE sale ADD CONSTRAINT sale_pk PRIMARY KEY ( sale_id );

ALTER TABLE artist
    ADD CONSTRAINT artist_artist FOREIGN KEY ( artist_code1 )
        REFERENCES artist ( artist_code );

ALTER TABLE artwork
    ADD CONSTRAINT artist_artwork FOREIGN KEY ( artist_code )
        REFERENCES artist ( artist_code );

ALTER TABLE artwork
    ADD CONSTRAINT artmedia_artwork FOREIGN KEY ( art_media_id )
        REFERENCES artwork_media ( art_media_id );

ALTER TABLE artwork
    ADD CONSTRAINT artstyle_artwork FOREIGN KEY ( art_style_id )
        REFERENCES artwork_style ( art_style_id );

ALTER TABLE exhibit
    ADD CONSTRAINT artwork_exhibit FOREIGN KEY ( art_number,
                                                 artist_code )
        REFERENCES artwork ( art_number,
                             artist_code );

ALTER TABLE history
    ADD CONSTRAINT artwork_history FOREIGN KEY ( art_number,
                                                 artist_code )
        REFERENCES artwork ( art_number,
                             artist_code );

ALTER TABLE sale
    ADD CONSTRAINT customer_sale FOREIGN KEY ( cust_id )
        REFERENCES customer ( cust_id );

ALTER TABLE sale
    ADD CONSTRAINT exhibit_sale FOREIGN KEY ( exhibit_no )
        REFERENCES exhibit ( exhibit_no );

ALTER TABLE exhibit
    ADD CONSTRAINT gallery_exhibit FOREIGN KEY ( gal_id )
        REFERENCES gallery ( gal_id );

ALTER TABLE history
    ADD CONSTRAINT gallery_history FOREIGN KEY ( gal_id )
        REFERENCES gallery ( gal_id );

SPOOL OFF
set echo off

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             9
-- CREATE INDEX                             0
-- ALTER TABLE                             23
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
